#!/bin/bash
#Darey.io AUX PROJECT 1
#This script is written by Akinmoyero Gabriel

#This will create the group Developers
echo 
sudo groupadd developers
#Check if the group is created 
sudo cat /etc/group | grep developers
echo
for name in `cat /home/ubuntu/Shell/names.csv`
do
       echo "Creating user $name"
       #Set the user default shell group and other groups
       sudo useradd -s /bin/bash -G developers -m -d /home/$name -U $name
       #check if the user is created 
       sudo cat /etc/passwd | grep $name
       id $name
       sleep 5
       #Create authorized_key file where I will move the public key to
       mkdir /home/$name/.ssh/ && touch /home/$name/.ssh/authorized_key
       cp /home/ubuntu/.ssh/id_rsa.pub /home/$name/.ssh/authorized_keys 
       cat /home/$name/.ssh/authorized_keys
done
echo
echo
#Keep it short keep it simple
