#!/bin/bash
#Darey.io AUX PROJECT 1
#This script is written by Akinmoyero Gabriel

#!/usr/bin/bash

names_path="./names.csv"
group_name="developers"
name=$USER
key_pair_name=key_pair

# Generate key-pair

ssh-keygen -f $key_pair_name
if cat /etc/group | grep $group_name; then
echo "Group exists"
else
sudo groupadd $group_name
fi

for name in `cat $names_path`
do
  if cat /etc/passwd | grep $name; then
   echo "${name} user exists"
    else
        sudo useradd -s /bin/bash -G $group_name -m -d /home/$name -U $name
        sudo mkdir -p /home/$name/.ssh
        sudo cp ${key_pair_name}.pub /home/$name/.ssh/authorized_keys
fi
done



#Keep it short keep it simple
